falter-policyrouting: apply patches from freifunk-firmware
Patches:
https://github.com/freifunk-berlin/firmware/tree/master/patches/packages/freifunk

Signed-off-by: Nick Hainke <vincent@systemli.org>

diff --git a/packages/falter-policyrouting/files/etc/hotplug.d/iface/30-policyrouting b/packages/falter-policyrouting/files/etc/hotplug.d/iface/30-policyrouting
--- a/packages/falter-policyrouting/files/etc/hotplug.d/iface/30-policyrouting
+++ b/packages/falter-policyrouting/files/etc/hotplug.d/iface/30-policyrouting
@@ -1,10 +1,13 @@
 #!/bin/sh
 
+[ "$INTERFACE" = wan ] && exit
+[ "$INTERFACE" = ffuplink ] && exit
+
 . /lib/functions.sh
 . /lib/functions/network.sh
 
 proto="4"
-[ -f /proc/net/ipv6_route ] && proto="4 6"
+#[ -f /proc/net/ipv6_route ] && proto="4 6"
 
 config_load freifunk-policyrouting
 config_get enable pr enable
@@ -13,15 +16,29 @@ config_get strict pr strict
 config_get zones pr zones
 
 if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
-	network_get_subnet net $INTERFACE
-	network_get_subnet6 net6 $INTERFACE
-	network_get_physdev dev $INTERFACE
+	case $(uci get network.${INTERFACE}.proto) in none)
+		# ubus status/netifd does not output ip4addr if proto=none
+		net=$(ip -4 addr show dev ${DEVICE} scope global|sed -n '2s,^[[:space:]]\+inet \([^[:space:]]\+\).*,\1,p')
+		#net6=$(ip -6 addr show dev ${DEVICE} scope global|sed -n '2s,^[[:space:]]\+inet6 \([^[:space:]]\+\).*,\1,p')
+	;;*)
+		network_get_subnet net $INTERFACE
+		#network_get_subnet6 net6 $INTERFACE
+	;;esac
 
-	if [ "$net" != "" -a -n "$dev" ]; then
+	if [ "$net" != "" -a -n "${DEVICE}" ]; then
 		eval $(/bin/ipcalc.sh $net)
 		if [ "$PREFIX" != "0" -a "$NETWORK" != "127.0.0.0" ]; then
-			if [ ! "$(ip r s t localnets |grep "$NETWORK/$PREFIX dev")" ]; then
-				cmd="ip r a $NETWORK/$PREFIX dev $dev table localnets"
+			if [ ! "$(ip route show table localnets |grep "$NETWORK/$PREFIX dev")" ]; then
+				cmd="ip route add $NETWORK/$PREFIX dev ${DEVICE} table localnets"
+				$cmd
+				if [ "$?" = 0 ]; then
+					logger -s -t policyrouting "Add route: $cmd"
+				else
+					logger -s -t policyrouting "Error! Could not add route: $cmd"
+				fi
+			fi
+			if [ ! "$(ip route show table olsr |grep "$NETWORK/$PREFIX dev")" ]; then
+				cmd="ip route add $NETWORK/$PREFIX dev ${DEVICE} table olsr"
 				$cmd
 				if [ "$?" = 0 ]; then
 					logger -s -t policyrouting "Add route: $cmd"
@@ -33,7 +50,7 @@ if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
 		fi
 
 		if [ -n "$net6" ]; then
-			cmd="ip -6 r a $net6 dev $dev table localnets"
+			cmd="ip -6 route add $net6 dev ${DEVICE} table localnets"
 			$cmd 2>&1 > /dev/null
 			if [ "$?" = 0 ]; then
 				logger -s -t policyrouting "Add route: $cmd (IPv6)"
@@ -52,51 +69,29 @@ if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
 		for n in $networks; do
 			if [ "$INTERFACE" = "$n" ]; then
 				for p in $proto; do
-					if [ ! "$(ip -$p ru s | grep "from all iif $dev lookup olsr-default")" ]; then
-						ip -$p rule add dev "$dev" lookup olsr-default prio 20000
-						if [ "$strict" != 0 ]; then
-							ip -$p rule add dev "$dev" unreachable prio 20001
-						fi
-						if [ "$?" = 0 ]; then
-							logger -s -t policyrouting "Use mesh gateway for interface $dev (IPv$p)"
-							if [ -z "$(uci -P /var/state get freifunk-policyrouting.${INTERFACE})" ]; then
-								uci -P /var/state set freifunk-policyrouting.${INTERFACE}="state"
-							fi
-							uci -P /var/state set freifunk-policyrouting.${INTERFACE}.device="$dev"
-						else
-							logger -s -t policyrouting "Error: Could not add rule: dev "$dev" lookup olsr-default prio 20000 (IPv$p)"
-						fi
-					fi
-				done
-			fi
-		done
-	fi
+					logger -s -t policyrouting "Use mesh gateway for interface ${DEVICE} (IPv$p)"
 
-fi
-
-if [ "$ACTION" = "ifdown" ]; then
-	dev="$(uci -q -P /var/state get freifunk-policyrouting.${INTERFACE}.device)"
-	if [ -n "$dev" ]; then
-		networks=""
-		for z in $zones; do
-			network_zone="$(uci -q get firewall.zone_${z}.network)"
-			if [ -z "$network_zone" ]; then
-				network_zone="$z"
-			fi
-			networks="$networks $network_zone"
-		done
-		for n in $networks; do
-			if [ "$INTERFACE" = "$n" ]; then
-				for p in $proto; do
-					if [ "$(ip -$p ru s | grep "from all iif $dev lookup olsr-default")" ]; then
-						ip -$p rule del dev "$dev" lookup olsr-default prio 20000
-						ip -$p rule del dev "$dev" unreachable prio 20001
-						if [ "$?" = 0 ]; then
-							logger -s -t policyrouting "Remove rule: dev "$dev" lookup olsr-default prio 20000 (IPv$p)"
-						else
-							logger -s -t policyrouting "Error! Could not remove rule: dev "$dev" lookup olsr-default prio 20000 (IPv$p)"
-						fi
+					# add olsr-tunnel rule (SmartGateway tunnel) if not present
+					if [ ! "$(ip -$p rule show | egrep "from all iif ${DEVICE} (\[detached\] )?lookup olsr-tunnel")" ]; then
+						ip -$p rule add dev "${DEVICE}" lookup olsr-tunnel prio 19999
 					fi
+
+					# add olsr-default rule (Default route from mesh) if not present
+					if [ ! "$(ip -$p rule show | egrep "from all iif ${DEVICE} (\[detached\] )?lookup olsr-default")" ]; then
+						ip -$p rule add dev "${DEVICE}" lookup olsr-default prio 20000
+					fi
+
+					# add unreachable rules (prevents using router's default route (without VPN))
+					if [ "$strict" != 0 ] && [ ! "$(ip -$p rule show | egrep "from all iif ${DEVICE} (\[detached\] )?unreachable")" ]; then
+						ip -$p rule add dev "${DEVICE}" unreachable prio 20001
+					fi
+
+					# uci stuff
+					if [ -z "$(uci -P /var/state get freifunk-policyrouting.${INTERFACE})" ]; then
+						uci -P /var/state set freifunk-policyrouting.${INTERFACE}="state"
+					fi
+					uci -P /var/state set freifunk-policyrouting.${INTERFACE}.device="${DEVICE}"
+
 				done
 			fi
 		done
